import type { Lead } from '@/lib/types';

export const mockLeads: Lead[] = [
  {
    id: '1',
    companyName: 'Innovate Inc.',
    logoUrl: 'https://placehold.co/40x40.png',
    companyDescription: 'A leading provider of innovative tech solutions.',
    arr: 5000000,
    employeeCount: 150,
    hq: 'San Francisco, CA',
    industry: 'Technology',
    keywords: ['SaaS', 'AI', 'Big Data'],
  },
  {
    id: '2',
    companyName: 'HealthWell',
    logoUrl: 'https://placehold.co/40x40.png',
    companyDescription: 'Dedicated to improving healthcare through technology.',
    arr: 12000000,
    employeeCount: 300,
    hq: 'Boston, MA',
    industry: 'Healthcare',
    keywords: ['HealthTech', 'Telemedicine'],
    score: 88,
    reason: 'High ARR and strong presence in a key market.',
    lastScored: '2023-10-26',
  },
  {
    id: '3',
    companyName: 'FinSecure',
    logoUrl: 'https://placehold.co/40x40.png',
    companyDescription: 'Cybersecurity solutions for the financial sector.',
    arr: 8000000,
    employeeCount: 200,
    hq: 'New York, NY',
    industry: 'Finance',
    keywords: ['FinTech', 'Cybersecurity'],
  },
  {
    id: '4',
    companyName: 'EcoPlanet',
    logoUrl: 'https://placehold.co/40x40.png',
    companyDescription: 'Sustainable solutions for a greener world.',
    arr: 3000000,
    employeeCount: 80,
    hq: 'Austin, TX',
    industry: 'Sustainability',
    keywords: ['GreenTech', 'Renewable Energy'],
  },
  {
    id: '5',
    companyName: 'RetailNext',
    logoUrl: 'https://placehold.co/40x40.png',
    companyDescription: 'AI-powered analytics for retail stores.',
    arr: 7500000,
    employeeCount: 250,
    hq: 'Chicago, IL',
    industry: 'Retail',
    keywords: ['RetailTech', 'Analytics'],
    score: 92,
    reason: 'Excellent fit for our portfolio, strong growth signals.',
    lastScored: '2023-10-25',
  },
  {
    id: '6',
    companyName: 'LearnSphere',
    logoUrl: 'https://placehold.co/40x40.png',
    companyDescription: 'Online learning platform for K-12 education.',
    arr: 4000000,
    employeeCount: 120,
    hq: 'Seattle, WA',
    industry: 'Education',
    keywords: ['EdTech', 'E-learning'],
  },
  {
    id: '7',
    companyName: 'TravelWize',
    logoUrl: 'https://placehold.co/40x40.png',
    companyDescription: 'Corporate travel management software.',
    arr: 6000000,
    employeeCount: 180,
    hq: 'London, UK',
    industry: 'Travel',
    keywords: ['SaaS', 'Corporate Travel'],
  },
  {
    id: '8',
    companyName: 'AutoMotion',
    logoUrl: 'https://placehold.co/40x40.png',
    companyDescription: 'Software for autonomous vehicle development.',
    arr: 20000000,
    employeeCount: 500,
    hq: 'Palo Alto, CA',
    industry: 'Automotive',
    keywords: ['DeepTech', 'AI', 'Autonomous Driving'],
    score: 75,
    reason: 'Large company, but potentially high-value target.',
    lastScored: '2023-10-24',
  },
];
